### ISSUE TITLE
Add `published_purls`

### ISSUE THREAD

**Issue by JLLeitschuh** [ossf/security-insights-spec#20]
It can sometimes be difficult to determine the mapping between a repository and the PURLs that it publishes. It would be useful if this file could communicate that it is the repository source of a certain set of PURLs.

**Comment by luigigubello** [comment]
You are right, I will improve the regex to match `pkg:` :)

**Comment by luigigubello** [comment]
> Why not just use `purl` instead of requiring those fields?

@JLLeitschuh no good reason,  you are right, so I proceed to open a PR to improve this, but before merging it I would prefer to share this change in OpenSSF Slack channel :)
