### ISSUE TITLE
Extend or adjust schema based on CNSS feedback

### ISSUE THREAD

**Issue by eddie-knight** [ossf/security-insights-spec#26]
Several suggestions have arisen, through discussions had by the [Cloud Native Security Slam](https://community.cncf.io/cloud-native-security-slam/) metrics committee. The committee is formed of security-minded open source maintainers and informed by CNCF's TAG Security recommendations, with the goal of increasing the security hygiene for CNCF projects.

Each of these suggestions relate to metrics we will be evaluating during the upcoming Slam in October and November. If we are able to implement these suggestions to the schema, the committee believes that it will benefit the community to include Security Insights as a requirement for participating projects to streamline evaluation during the event.

I will be raising discussion on slack, and I'll use this GitHub Issue to keep track of suggestions as I create additional issues with suggestions. Please let me know if I can answer any questions about the overall intent behind these suggestions.

- #25
- #27
- #28
- #29
- #30

**Comment by luigigubello** [comment]
Hi @eddie-knight thanks for the detailed issue :raised_hands: 

> Several suggestions have arisen, through discussions had by the [Cloud Native Security Slam](https://community.cncf.io/cloud-native-security-slam/) metrics committee

:partying_face: 

- https://github.com/ossf/security-insights-spec/issues/25: it sounds good to me, I can open a PR this week or you can open a PR and add me as reviewer :) 
- https://github.com/ossf/security-insights-spec/issues/27: I have [answered](https://github.com/ossf/security-insights-spec/issues/27#issuecomment-1705800795) in the issue
- https://github.com/ossf/security-insights-spec/issues/28: I have answered [[1](https://github.com/ossf/security-insights-spec/issues/28#issuecomment-1705802443) - [2](https://github.com/ossf/security-insights-spec/issues/28#issuecomment-1705807263)] in the issue
- https://github.com/ossf/security-insights-spec/issues/29: I have [answered](https://github.com/ossf/security-insights-spec/issues/29#issuecomment-1705812508) in the issue :)
- https://github.com/ossf/security-insights-spec/issues/30: I have [answered](https://github.com/ossf/security-insights-spec/issues/30#issuecomment-1705793605) in the issue
- https://github.com/ossf/security-insights-spec/issues/31: I have also [answered](https://github.com/ossf/security-insights-spec/issues/31#issue-1875747216) into issue#31, honestly I think it is an important issue and we should prioritize it.

I will start to prepare changes and draft PRs this week :raised_hands: (I hope)
