### ISSUE TITLE
Extend the Security Artifacts schema

### ISSUE THREAD

**Issue by eddie-knight** [ossf/security-insights-spec#30]
This is part of #26 

Currently, the Security Artifacts section only contains a schema entry for a project's threat model. It may prove beneficial to allow users to report on the state of their self assessment (a document that is recommended within the CNCF).

Current example:
```yaml
security-artifacts:
  threat-model:
    threat-model-created: true
    evidence-url:
    - https://foo.com/model.html
    comment: |
      Lorem ipsum dolor sit amet, consectetur adipisci elit,
      sed do eiusmod tempor incidunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrum exercitationem ullamco laboriosam,
      nisi ut aliquid ex ea commodi consequatur. Duis aute irure reprehenderit
      in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
      sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt
      mollit anim id est laborum
```

The new value would be similar to the existing one, but with a change in name from `threat-model` to `self-assessment`.

**Comment by eddie-knight** [comment]
Hmm... I previously overlooked the `security-assessments` section.

Why are these separate? It seems like a security assessment will always result in a security artifact... but am I wrong to lump assessments into the security artifacts category?

**Comment by luigigubello** [comment]
Technically - but this is just the initial name convention - `security-assessments` is for third-party auditors' evidence (e.g. pentest report, security certifications, etc), and `security-artifacts` is for generic artifacts, so also self-assessments (even if, at the moment, `security-artifacts` has only `threat-model`).

So, I would have two proposals here:

1. Add two new keys in `security-artifacts`: 
  a. `self-assessment`: this should cover CNCF recommendation
  b. `generic-artifact`: this should help SECURITY INSIGHTS consumers that want to add other artifacts.
2. Point 1, but we add just the key `self-assessment`.

I prefer 1), what do you think?

**Comment by eddie-knight** [comment]
@luigigubello The first option sounds good to me! I like the idea of allowing for ad-hoc `generic-artifact` entries to support whatever strategy a user might come up with.

I'll put up a PR for this soon.
