### ISSUE TITLE
Refine the versioning process

### ISSUE THREAD

**Issue by eddie-knight** [ossf/security-insights-spec#31]
I'm currently creating the Security Documentation course that will be distributed by Linux Foundation Training & Certification alongside the the Cloud Native Security Slam kickoff. It would be beneficial for me to be able state which version of the specification I am referencing, to avoid reader confusion in the event that changes are made to the spec after the course is published. 

**As a course author, I would like to have a schema version that I can reference when writing about the contents of the specification.**

## Proposed Changes

Instead of versioning the schema within the file name, the schema should be maintained as a software artifact, with formal releases made through the GitHub Release feature.

Here is an example of that approach, from OpenSSF's S2C2F:
https://github.com/ossf/s2c2f/releases/tag/v1.1

To implement this change, we would modify the file name for the schema to `security-insights-schema.yml`, then make a tagged release of `v1.0`.

**Comment by luigigubello** [comment]
YES! This! This is one of the next steps for SECURITY INSIGHTS, formalization of the versioning process (major vs minor updates, changelog, timeframe for the new version, etc). I can try to write an initial policy, or - if you have a good and lean one - feel free to propose it or link it to the issue.
