### ISSUE TITLE
Add CI for schema

### ISSUE THREAD

**Issue by luigigubello** [ossf/security-insights-spec#49]
Add GA to validate the examples according to the branch schema before merging.

**Comment by eddie-knight** [comment]
This will depend on tooling from https://github.com/ossf/si-tooling

**Comment by eddie-knight** [comment]
This is now accomplished in a simple `cue vet` added in a CI workflow via #96

https://github.com/ossf/security-insights-spec/blob/main/.github/workflows/ci.yml#L22-L26
