### ISSUE TITLE
Cut v1.0.0 release

### ISSUE THREAD

**Issue by eddie-knight** [ossf/security-insights-spec#58]
The v1.0.0 release is scheduled for Monday October 2, 2023.

Ideally, we will have the following elements complete, with automation where possible:
- Artifacts (spec, validator, source)
- Release notes
- Release signature

(Am I missing anything?)

**Comment by luigigubello** [comment]
#61 - We have decided to move the validator and other tools to different repos, so this repo can be used just for the specification and examples.

**Comment by luigigubello** [comment]
Currently, signing of the specification is not required and in scope, but we can evaluate this for the next releases.

**Comment by eddie-knight** [comment]
Agreed. This seems to be skipped within our sister non-code project as well: https://github.com/ossf/s2c2f/releases
