### ISSUE TITLE
Consider adding a "sponsorship" attribute to the spec

### ISSUE THREAD

**Issue by scovetta** [ossf/security-insights-spec#88]
Idea -- some projects have FUNDING.yml or repository properties that suggest the maintainer is interested in accepting sponsorship of some sort. It might be reasonable to add this to the SI spec.

**Comment by emmairwin** [comment]
following

**Comment by eddie-knight** [comment]
I've drafted this into #96 as `project: funding: https://foo.bar/FUNDING.yml`

**Comment by eddie-knight** [comment]
Thanks for this suggestion @scovetta!

The [project funding](https://github.com/ossf/security-insights-spec/blob/main/specification-details/project.md#projectfunding-optional) field will be included in the upcoming release (#97)
