### ISSUE TITLE
Spec unreadable due to typo in URL ("specificaion")

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/security-insights-spec#91]
Most of the specification at: https://github.com/ossf/security-insights-spec/blob/main/specification.md

does not work, because most of the links to portions use the typo "specificaion" instead of "specification" (missing "t"). E.g., this link fails:
https://github.com/ossf/security-insights-spec/blob/main/specificaion/contribution-policy.md

**Comment by eddie-knight** [comment]
Thanks for catching this and opening a PR!
